package me.osama.TaskManager.tasks;

import java.io.Serializable;

public class Task implements Serializable{
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 5527258407135652423L;
	
	private long id;
	private String name;
	private boolean complete;
	private String description;

	public Task(String taskName) {
		name = taskName;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setComplete(boolean complete) {
		this.complete = complete;
	}

	public boolean isComplete() {
		return complete;
	}
	
	public void toggleComplete() {
		complete = !complete;
	}

	public String toString() {
		return name;
	}
	
	public long getId (){
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	
	public String getDescription() {
		return description;
	}

	
	public void setDescription(String description) {
		this.description = description;
	}
	
}
